### ISSUE TITLE
Support working outside GOPATH

### ISSUE THREAD

**Issue by bitfield** [jimmyfrasche/autoreadme#7]
```
autoreadme
Could not create README.md for /Users/john/git/bitfield/script because: Not in go root or element of $GOPATH: /Users/john/git/bitfield/script
```

**Comment by jimmyfrasche** [comment]
I would like to support Go modules but am not sure of the best approach yet. I think it may require a version 2 of the command. My rambling thoughts about this are listed below.

Supporting modules means  moving from `go/build` to either `go/packages` or invoking `go list` directly. `go/packages` is nice except for tools like this that stick to the `go` convention of one package = one directory (since it allows multiple build systems). Using `go list` directly may simplify things.

Those both entail a performance hit per invocation of autoreadme so I'd probably want to remove the `-f` and `-r` (force and recursive) flags and make that how it always works, or at least how it works by default.

At that point it would be best to work on the entire repo at once. One way to do that would be to search up until I find a `.git` directory then search back down until I find all the directories that contain `go.mod` (with a fallback for legacy `$GOPATH`) and use that to determine what queries to give `go/packages`/`go list`. Alternately, I suppose it could take `go list` query defaulting to `./...` run from the repo root.

No one wants to janitor readmes where only the timestamp has changed so I'd have to remove that from the default template (admittedly, I have no idea why I included in the first place).

It would also mean there would probably need to be a scheme for using the same template for multiple packages (README.md.template applies to all child directories without a template? Not helpful if you have multiple subdirs that need the same template but want it to be different than the parent's.)

And an ignore file for directories to skip in addition to vendor/testdata (which `-r` incorrectly fails to skip at present) or there would, at least, need to be some heuristics for skipping directories with a manually created readme.

As long as I'm at it I'd probably replace `-template` and `-print-template` with something that just writes `README.md.template` in the current directory and have that and whatever mechanism for applying the same template to multiple directories be the single mechanism for providing a template.

**Comment by bitfield** [comment]
Can't we let `go doc` do all the heavy lifting?

**Comment by jimmyfrasche** [comment]
That's an interesting thought. `go doc` didn't exist when this was created. But it only works a package at a time and the output would need to be parsed so I'm not sure that really buys anything. The parts that are hard are still hard.

**Comment by bitfield** [comment]
It depends what you want from the tool. I came here because I was looking for a way to avoid duplicating the inline documentation in my package as a README file. Ideally, I'd write all my package and identifier comments and examples, run one command, and it would generate a README which represents a Markdown-formatted version of what `go doc` would output.

Things like 'walking the directory tree to determine what is the module root' and so on are all problems which are solved by `go doc`. If I were implementing this tool I certainly wouldn't try to do that.

No doubt there's scope for a much more ambitious tool, but what I've described would solve the problem _I_ have.

**Comment by jimmyfrasche** [comment]
While what I describe would be more ambitious than the current version, it's less a matter of ambition than of correctness† and mapping the tool's current feature set from GOPATH-world to modules-world, with some concerns for efficiency.

† consider a repository that contains multiple go modules or a go module and a lot of non-Go code

Using `go doc` would create more problems than it would solve. Extracting the documentation from a package isn't the hard part. That's solved so having to write a new parser for the output of `go doc` would take more time than anything I described above. To handle cases like multi-module repos I'd probably have to do most of what I described above anyway and it would be much slower since it has to invoke the `go` command for each package in each module in the repository.

I certainly plan on supporting modules but I don't want to leave important design considerations unmet out of haste. This discussion has helped me narrow a lot of those down already, but I still need to take some time to explore and experiment with them before I commit to anything. The code to write isn't the bottleneck here; it's deciding which code to write.

**Comment by jimmyfrasche** [comment]
Created a new branch (will become the default branch soon-ish) that fixes this.

**Comment by bitfield** [comment]
I tried running the tip of `main` in one of my projects, https://github.com/bitfield/gotestdox. Although I didn't get the "Not in go root" error, I also didn't get most of the documentation. Here's the output:

```
# gotestdox
[![Go Reference](https://pkg.go.dev/badge/github.com/bitfield/gotestdox.svg)](https://pkg.go.dev/github.com/bitfield/gotestdox)

```shell
go get github.com/bitfield/gotestdox
```




---
Automatically generated by [autoreadme](https://github.com/jimmyfrasche/autoreadme)
```

Would you expect there to be more documentation shown here?

**Comment by jimmyfrasche** [comment]
In that case, no. The primary source is the standard package documentation and there is none so it is working as designed. (You can also attach go/doc/comment style comments to the module directive in go.mod and provide arbitrary additional data and templates)

**Comment by bitfield** [comment]
Ah, in that case I've completely misunderstood what `autoreadme` is intended to do. I assumed it would build the README from the documentation comments on the types, functions, and other identifiers in the package, in the same way that `pkgsite` does:

https://pkg.go.dev/github.com/bitfield/gotestdox

It sounds like you're saying it looks only for the documentation comment at package level, and ignores everything else, is that correct?

**Comment by jimmyfrasche** [comment]
That's largely correct. There are a few other things it pulls into the overridable templates that are not used by pkgsite but the package level documentation is 99% of it. It's not meant to replace pkgsite.

**Comment by bitfield** [comment]
Fair enough. It's important to be clear about what you are and aren't trying to build. I think you might find, though, that most developers have put the bulk of their documentation efforts into the per-item comments, and very little into a package-level comment (though that's certainly worth including too, if present).
